version: 2.1

jobs:
  quality-check:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --freeze-lockfile
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Prettier
          command: yarn prettier --check "src/**/*.js"
      - run:
          name: Unit test
          command: yarn test
  deploy:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --freeze-lockfile
      - run:
          name: Build
          command: yarn build
      - run:
          name: Deploy to Github pages
          command: yarn deploy:ci

workflows:
  version: 2.1
  pr:
    jobs:
      - quality-check:
          filters:
            branches:
              ignore: master
  master:
    jobs:
      - quality-check:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - quality-check
