version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --freeze-lockfile
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Prettier
          command: yarn prettier --check "src/**/*.js"

workflows:
  version: 2.1
  build:
    jobs:
      - test
